/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author Zaki
 */
public class FriendsPages extends javax.swing.JPanel {

    /**
     * Creates new form FriendsPages
     */
    public FriendsPages() {
        initComponents();
        this.currentFriendsPanel.setLayout(new BoxLayout (this.currentFriendsPanel, BoxLayout.Y_AXIS));
        this.friendRequestsPanel.setLayout(new BoxLayout (this.friendRequestsPanel, BoxLayout.Y_AXIS));
        this.suggestedFriendsPanel.setLayout(new BoxLayout (this.suggestedFriendsPanel, BoxLayout.Y_AXIS));
        this.searchedFriendsPanel.setLayout(new BoxLayout (this.suggestedFriendsPanel, BoxLayout.Y_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        currentFriendsPanel = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        friendRequestsPanel = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        suggestedFriendsPanel = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        searchCriteriaField = new javax.swing.JTextField();
        searchedFriendsPanel = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(576, 536));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(576, 536));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(576, 536));

        currentFriendsPanel.setBackground(new java.awt.Color(255, 255, 255));
        currentFriendsPanel.setMinimumSize(new java.awt.Dimension(564, 489));
        currentFriendsPanel.setPreferredSize(new java.awt.Dimension(489, 564));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentFriendsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentFriendsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Current Friends", jPanel1);

        friendRequestsPanel.setBackground(new java.awt.Color(255, 255, 255));
        friendRequestsPanel.setMinimumSize(new java.awt.Dimension(564, 489));
        friendRequestsPanel.setPreferredSize(new java.awt.Dimension(564, 489));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(friendRequestsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(friendRequestsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Friend Requests", jPanel2);

        suggestedFriendsPanel.setBackground(new java.awt.Color(255, 255, 255));
        suggestedFriendsPanel.setMinimumSize(new java.awt.Dimension(564, 489));
        suggestedFriendsPanel.setPreferredSize(new java.awt.Dimension(564, 489));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(suggestedFriendsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(suggestedFriendsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Suggested Friends", jPanel3);

        searchButton.setText("Search");

        searchedFriendsPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchedFriendsPanel.setMinimumSize(new java.awt.Dimension(564, 460));
        searchedFriendsPanel.setPreferredSize(new java.awt.Dimension(564, 460));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchedFriendsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(searchCriteriaField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchCriteriaField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchedFriendsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search For Friends", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    public void addToCurrentFriendsPanel (JPanel panel) {
        this.currentFriendsPanel.add(panel);
    }
    public void removeAllCurrentFriendsPanel () {
        this.currentFriendsPanel.removeAll();
    }
    
    public void addToFriendRequestsPanel (JPanel panel) {
        this.friendRequestsPanel.add(panel);
    }
    public void removeAllFriendRequestsPanel () {
        this.friendRequestsPanel.removeAll();
    }
    
    public void addToSuggestedFriendsPanel (JPanel panel) {
        this.suggestedFriendsPanel.add(panel);
    }
    public void removeAllSuggestedFriendsPanel () {
        this.suggestedFriendsPanel.removeAll();
    }
    
    public void addToSearchedFriendsPanel (JPanel panel) {
        this.searchedFriendsPanel.add(panel);
    }
    public void removeAllSearchedFriendsPanel () {
        this.searchedFriendsPanel.removeAll();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane currentFriendsPanel;
    private javax.swing.JScrollPane friendRequestsPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchCriteriaField;
    private javax.swing.JScrollPane searchedFriendsPanel;
    private javax.swing.JScrollPane suggestedFriendsPanel;
    // End of variables declaration//GEN-END:variables
}
