/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.User;
import backend.UserDB;
import backend.groups.Group;
import backend.groups.GroupContentManager;
import backend.groups.GroupRole;
import java.awt.BorderLayout;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author Zaki
 */
public class GroupDetails extends javax.swing.JFrame {

    /**
     * Creates new form GroupDetails
     */
    
    private User user;
    private Group group;
    private GroupRole role;
    
    public GroupDetails(User user, Group group, GroupRole role) {
        initComponents();
        
        this.user = user;
        this.group = group;
        this.role = role;
        
        JPanel membersPanel = new JPanel();
        membersPanel.setLayout(new BoxLayout (membersPanel, BoxLayout.Y_AXIS));
        this.groupMembersDetailsPanel.setLayout(new BorderLayout ());
        for (String userID : this.group.getAllMembers()) {
            membersPanel.add(new FriendsPanel (user, UserDB.getInstance().searchUserByUserId(userID), null, "Group", getWidth(), 150, this.group));
        }
        this.groupMembersDetailsPanel.add(new JScrollPane (membersPanel, ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER));
        this.groupMembersDetailsPanel.revalidate();
        this.groupMembersDetailsPanel.repaint();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        groupMembersDetailsPanel = new javax.swing.JPanel();
        groupPostsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(588, 583));
        setPreferredSize(new java.awt.Dimension(588, 583));
        setSize(new java.awt.Dimension(588, 583));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout groupMembersDetailsPanelLayout = new javax.swing.GroupLayout(groupMembersDetailsPanel);
        groupMembersDetailsPanel.setLayout(groupMembersDetailsPanelLayout);
        groupMembersDetailsPanelLayout.setHorizontalGroup(
            groupMembersDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        groupMembersDetailsPanelLayout.setVerticalGroup(
            groupMembersDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Members", groupMembersDetailsPanel);

        javax.swing.GroupLayout groupPostsPanelLayout = new javax.swing.GroupLayout(groupPostsPanel);
        groupPostsPanel.setLayout(groupPostsPanelLayout);
        groupPostsPanelLayout.setHorizontalGroup(
            groupPostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        groupPostsPanelLayout.setVerticalGroup(
            groupPostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Posts", groupPostsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GroupDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GroupDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GroupDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GroupDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GroupDetails().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel groupMembersDetailsPanel;
    private javax.swing.JPanel groupPostsPanel;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
